import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Import a module that doesn't exist
import { SomeComponent } from "./non-existent-module";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Type error: wrong type assignment
const numberValue: number = "this is a string";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Invalid property that doesn't exist on Metadata type
  invalidProperty: true,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
